In [1]:
%matplotlib inline
from __future__ import print_function
import torch

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



Construct a 5x3 matrix, uninitialized:



In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 1.7395e-04,  8.3092e+20,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.3452e-43],
        [ 0.0000e+00,  0.0000e+00,  9.2196e-41],
        [ 0.0000e+00,  4.8555e+33, -3.1116e-13]])


Construct a randomly initialized matrix:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0188, 0.0019, 0.5305],
        [0.0120, 0.4724, 0.7232],
        [0.7315, 0.4915, 0.1487],
        [0.5252, 0.6465, 0.9759],
        [0.9055, 0.2770, 0.5906]])


Construct a matrix filled zeros and of dtype long:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.9083, -0.7730,  0.1751],
        [ 1.5005,  0.5208,  1.2926],
        [-0.2387,  0.9134,  0.3460],
        [-0.8335, -0.5693,  1.0653],
        [ 0.6653, -0.7125, -0.1019]])


Get its size:



In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.8319, -0.6017,  0.6990],
        [ 2.4234,  1.3518,  1.3514],
        [ 0.6040,  1.6526,  0.7574],
        [ 0.0599,  0.0803,  2.0531],
        [ 1.4383, -0.1959,  0.4691]])


Addition: syntax 2



In [9]:
print(torch.add(x, y))

tensor([[-0.8319, -0.6017,  0.6990],
        [ 2.4234,  1.3518,  1.3514],
        [ 0.6040,  1.6526,  0.7574],
        [ 0.0599,  0.0803,  2.0531],
        [ 1.4383, -0.1959,  0.4691]])


Addition: providing an output tensor as argument



In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.8319, -0.6017,  0.6990],
        [ 2.4234,  1.3518,  1.3514],
        [ 0.6040,  1.6526,  0.7574],
        [ 0.0599,  0.0803,  2.0531],
        [ 1.4383, -0.1959,  0.4691]])


Addition: in-place



In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.8319, -0.6017,  0.6990],
        [ 2.4234,  1.3518,  1.3514],
        [ 0.6040,  1.6526,  0.7574],
        [ 0.0599,  0.0803,  2.0531],
        [ 1.4383, -0.1959,  0.4691]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [12]:
print(x[:, 1])

tensor([-0.7730,  0.5208,  0.9134, -0.5693, -0.7125])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [13]:
import torch
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 4)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([4, 4])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.5717])
1.5716885328292847



### NumPy Bridge


Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([2.5717], device='cuda:0')
tensor([2.5717], dtype=torch.float64)


In [20]:
gpu = torch.device("cuda")
cpu = torch.device("cpu")

In [21]:
%%time
% reset -f
import torch

cpu = torch.device("cpu")
a = torch.randn(50000,30000, device=cpu)

CPU times: user 9.34 s, sys: 1.04 s, total: 10.4 s
Wall time: 10.4 s


In [22]:
%%time
% reset -f
import torch

gpu = torch.device("cuda")
b = torch.randn(50000,30000, device=gpu)

CPU times: user 51.2 ms, sys: 120 ms, total: 171 ms
Wall time: 168 ms


In [23]:
!nvidia-smi

Wed Oct  2 11:40:28 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 415.27       Driver Version: 415.27       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:65:00.0  On |                  N/A |
|  0%   51C    P5    24W / 275W |   9025MiB / 11175MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:B3:00.0 Off |                  N/A |
|  0%   38C    P8    10W / 275W |     12MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        

In [24]:
!uname -a

Linux AOT01 4.15.0-64-generic #73~16.04.1-Ubuntu SMP Fri Sep 13 09:56:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
