# Linear

In [1]:
import torch

input_num = 3   # 輸入維度
output_num = 2  # 輸出維度

func = torch.nn.Linear(input_num, output_num)

print(func.weight)
print(func.weight.shape)

print(func.bias)
print(func.bias.shape)

print(func(torch.randn(1,input_num)))


Parameter containing:
tensor([[ 0.5521,  0.4051, -0.0201],
        [-0.0336,  0.2190, -0.3925]], requires_grad=True)
torch.Size([2, 3])
Parameter containing:
tensor([0.4777, 0.3564], requires_grad=True)
torch.Size([2])
tensor([[1.6737, 0.4127]], grad_fn=<AddmmBackward>)


## Back Propagation with PyTorch

In [ ]:
import torch


x_data = [1.0, 2.0, 3.0]
y_data = [2.0, 4.0, 6.0]

w = torch.tensor([1.0],  requires_grad=True)  # Any random value

# our model forward pass


def forward(x):
    return x * w

# Loss function

def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) * (y_pred - y)

# Before training
print("predict (before training)", 4, forward(4).item())

# Training loop
for epoch in range(20):
    for x_val, y_val in zip(x_data, y_data):
        l = loss(x_val, y_val)
        l.backward()
        print("\tgrad: ", x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data

        # Manually zero the gradients after updating weights
    w.grad.data.zero_()

    print("progress:", epoch, l.data[0])

# After training
print("predict (after training)", 4, forward(4).data[0])


In [ ]:
import torch


x_data = [1.0, 2.0, 3.0]
y_data = [2.0, 4.0, 6.0]

w1 = torch.tensor([1.0],  requires_grad=True)  # Any random value
w2 = torch.tensor([1.0],  requires_grad=True) 
b = torch.tensor([1.0],  requires_grad=True) 
# our model forward pass


def forward(x):
    return x ** 2 * w2 + x * w1 + b

# Loss function

def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) * (y_pred - y)

# Before training
print("predict (before training)", 4, forward(4).data[0])

# Training loop
for epoch in range(100):
    for x_val, y_val in zip(x_data, y_data):
        l = loss(x_val, y_val)
        l.backward()
        print("\tgrad: ", x_val, y_val, w1.grad.data[0], w2.grad.data[0], b.grad.data[0])
    w1.data = w1.data - 0.01 * w1.grad.data
    w2.data = w2.data - 0.01 * w2.grad.data
    b.data = b.data - 0.01 * b.grad.data
    # Manually zero the gradients after updating weights
    w1.grad.data.zero_()
    w2.grad.data.zero_()
    b.grad.data.zero_()

    print("progress:", epoch, l.data[0])

# After training
print("predict (after training)", 4, forward(4).data[0])


# The 'pytorch' way

In [6]:
import torch
from tqdm import tqdm

x = torch.arange(1.0, 11.0, step=1, out=None)
y = torch.arange(2.0, 22.0, step=2, out=None)
x = x.view(10,-1)
y = y.view(10,-1)
# x = torch.tensor([[1.0], [2.0], [3.0], [4.0]]) 
# y = torch.tensor([[2.0], [4.0], [6.0], [8.0]])


class LinearRegressionModel(torch.nn.Module): 
    def __init__(self): 
        super(LinearRegressionModel, self).__init__() 
        self.linear = torch.nn.Linear(1, 1, bias=True)
  
    def forward(self, x): 
        y_pred = self.linear(x) 
        return y_pred 

our_model = LinearRegressionModel() 
  
criterion = torch.nn.MSELoss(reduction='mean') 
optimizer = torch.optim.SGD(our_model.parameters(), lr = 0.01)

for epoch in tqdm(range(5000)): 
  
    pred_y = our_model(x) 
  
    # Compute and print loss 
    loss = criterion(pred_y, y) 
  
    # Zero gradients, perform a backward pass,  
    # and update the weights. 
    optimizer.zero_grad() 
    loss.backward() 
    optimizer.step() 
    # print('epoch {}, loss {}'.format(epoch, loss.item())) 

new_var = torch.tensor([[100.0]]) 
pred_y = our_model(new_var) 
print("predict (after training)", 100, our_model(new_var).item()) 
print('weights = {}'.format(our_model.linear.weight.item()))
try:
    print('bias = {}'.format(our_model.linear.bias.item()))
except:
    print("No bias")

100%|██████████| 5000/5000 [00:01<00:00, 3885.12it/s]

predict (after training) 100 199.99996948242188
weights = 1.999999761581421
bias = 1.429742496839026e-06
