In [2]:
%matplotlib inline
from __future__ import print_function
import torch

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



Construct a 5x3 matrix, uninitialized:



In [12]:
x = torch.empty(5, 3)
print(x)

tensor([[-6.1588e-20,  4.5859e-41, -6.1588e-20],
        [ 4.5859e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


Construct a randomly initialized matrix:



In [13]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7647, 0.9498, 0.3544],
        [0.6462, 0.5719, 0.2398],
        [0.1674, 0.0492, 0.6381],
        [0.2214, 0.7974, 0.3842],
        [0.8815, 0.4859, 0.7961]])


Construct a matrix filled zeros and of dtype long:



In [14]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [15]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [16]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4475, -1.1630, -0.7247],
        [-0.6779, -1.6413, -1.3343],
        [-0.0868,  1.2982, -0.9390],
        [-0.4227, -0.0973, -0.8525],
        [ 0.0521, -0.0170,  0.4667]])


Get its size:



In [17]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [18]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.2643, -0.3223, -0.0262],
        [ 0.3037, -0.8066, -0.7107],
        [ 0.3034,  1.9468, -0.4152],
        [-0.4069,  0.3124, -0.7711],
        [ 0.5359,  0.3429,  0.9943]])


Addition: syntax 2



In [19]:
print(torch.add(x, y))

tensor([[ 1.2643, -0.3223, -0.0262],
        [ 0.3037, -0.8066, -0.7107],
        [ 0.3034,  1.9468, -0.4152],
        [-0.4069,  0.3124, -0.7711],
        [ 0.5359,  0.3429,  0.9943]])


Addition: providing an output tensor as argument



In [20]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.2643, -0.3223, -0.0262],
        [ 0.3037, -0.8066, -0.7107],
        [ 0.3034,  1.9468, -0.4152],
        [-0.4069,  0.3124, -0.7711],
        [ 0.5359,  0.3429,  0.9943]])


Addition: in-place



In [21]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.2643, -0.3223, -0.0262],
        [ 0.3037, -0.8066, -0.7107],
        [ 0.3034,  1.9468, -0.4152],
        [-0.4069,  0.3124, -0.7711],
        [ 0.5359,  0.3429,  0.9943]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [22]:
print(x[:, 1])

tensor([-1.1630, -1.6413,  1.2982, -0.0973, -0.0170])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [23]:
import torch
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 4)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([4, 4])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [24]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3050])
0.3050006628036499



### NumPy Bridge


Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array

In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [27]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [28]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [29]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.3050], device='cuda:0')
tensor([1.3050], dtype=torch.float64)


In [16]:
gpu = torch.device("cuda")
cpu = torch.device("cpu")

In [6]:
%%time
% reset -f
import torch

cpu = torch.device("cpu")
a = torch.randn(50000,30000, device=cpu)

CPU times: user 9.16 s, sys: 1.1 s, total: 10.3 s
Wall time: 10.3 s


In [7]:
%%time
% reset -f
import torch

gpu = torch.device("cuda")
b = torch.randn(50000,30000, device=gpu)

CPU times: user 54.6 ms, sys: 111 ms, total: 166 ms
Wall time: 164 ms
